name: learn-github-actions
on:
  push:
    branches: [main]
jobs:
  go-version-lab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4.1.0
        with:
          node-version: '16.x'
      - run: npm run install bats
      - run: run bats -v